# Generated by Django 2.2.14 on 2020-11-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administradores', '0001_initial'),
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=True)),
                ('job', models.CharField(max_length=200)),
                ('administrador', models.ManyToManyField(related_name='admnistrador', to='administradores.Administrador')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
            ],
        ),
    ]
